# Generated by Django 4.2.3 on 2023-07-18 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0005_alter_game_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 10, 10, 28, 275669, tzinfo=datetime.timezone.utc)),
        ),
    ]
