# Generated by Django 4.2.3 on 2023-07-19 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0007_alter_game_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elo',
            options={'verbose_name': 'Elo', 'verbose_name_plural': 'Scoreboard'},
        ),
        migrations.AddField(
            model_name='game',
            name='matchday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 9, 34, 10, 814112, tzinfo=datetime.timezone.utc)),
        ),
    ]
