# Generated by Django 4.2.3 on 2023-07-19 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0008_alter_elo_options_game_matchday_alter_game_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='preffered_position',
        ),
        migrations.AddField(
            model_name='player',
            name='match_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 11, 39, 45, 81514, tzinfo=datetime.timezone.utc)),
        ),
    ]
