# Generated by Django 4.2.3 on 2023-07-19 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0010_alter_game_deadline_alter_player_match_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='kebap_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 13, 42, 35, 355822, tzinfo=datetime.timezone.utc)),
        ),
    ]
